site_name: Dog's Roblox Style Guide
site_url: https://style.dgox.de
theme:
   name: material
   font:
      text: Merriweather Sans
      code: Red Hat Mono
   logo: assets/logo.png
   favicon: assets/favicon.ico
   features:
      - navigation.footer
   palette:
      scheme: default
      primary: blue
      accent: deep purple

markdown_extensions:
   - attr_list
   - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
   - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
   - pymdownx.inlinehilite
   - pymdownx.snippets
   - pymdownx.superfences:
        custom_fences:
           - name: mermaid
             class: mermaid
             format: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.tabbed:
        alternate_style: true
   - admonition
   - pymdownx.details

extra:
   social:
      - icon: simple/github
        link: https://github.com/dgxo
      - icon: simple/roblox
        link: https://www.roblox.com/users/361635687/profile

copyright: Copyright &copy; 2024 James Willett
